seed: 42

# autotuning
hyperopt_tuning: False
n_trials: 90

# data
# num_nodes: 51
val_ratio: 0.1
test_ratio: 0.1

normalizer: std
column_wise: True

# model:
lag: 7
horizon: 1

# input_dim: 20
output_dim: 1

embed_dim: 64
rnn_units: 128
num_layers: 2
cheb_k: 2

# train:
loss_func: mse

batch_size: 32
epochs: 300

lr_init: 0.00003209665415137032
lr_decay: False
lr_decay_rate: 0.3
lr_decay_step: 5,20,40,70

early_stop: True
early_stop_patience: 60

# dir
hydra:
  run:
    dir: outputs/AGCRN/${now:%Y-%m-%d_%H-%M-%S}
log_dir: outputs/AGCRN/${now:%Y-%m-%d_%H-%M-%S}

# wandb
wandb_dir: outputs/AGCRN/${now:%Y-%m-%d_%H-%M-%S}
run_name: ${now:%m-%d_%H-%M-%S}
wandb_mode: "run"

# data
# emissions: data/interim/emissions.csv
# eu_emissions: data/interim/eu_emi.csv
# us_emissions: data/interim/us_emi.csv

defaults:
  - dataset: CN

tmp: data/interim/ordered_province_daily.csv
aqi: data/interim/aqi.csv
save_arrays_EDA: False

device: cuda:0
log_step: 20
