seed: 42

# autotuning
hyperopt_tuning: False
n_trials: 90

# data
# num_nodes: 28 # 28 For EU, 31 for CN, 51 for US
val_ratio: 0.1
test_ratio: 0.1

normalizer: std # None
normalizd_col: 3
column_wise: True

# model:
lag: 7
horizon: 1

input_dim: 20
output_dim: 1

embed_dim: 32
rnn_units: 64 # 64
num_layers: 1 # 1
cheb_k: 3

# GRU layer
hidden_dim_node: 16 # 16
num_layers_node: 1

# attention layer
num_heads: 2
# train:
loss_func: mse

batch_size: 32
epochs: 300

lr_init: 4.225775196829383e-05
lr_decay: False
lr_decay_rate: 0.001
lr_decay_step: 150, 200

early_stop: True
early_stop_patience: 60

# dir
hydra:
  run:
    dir: outputs/AGCRN_time_dependent_matrix_laplacian/${now:%m-%d_%H-%M-%S}
log_dir: outputs/AGCRN_time_dependent_matrix_laplacian/${now:%m-%d_%H-%M-%S}

# wandb
wandb_dir: outputs/AGCRN_time_dependent_matrix_laplacian/${now:%m-%d_%H-%M-%S}
run_name: ${now:%m-%d_%H-%M-%S}
wandb_mode: "run"

# data

# In seperate files
# emissions: data/interim/emissions.csv
# eu_emissions: data/interim/eu_emi.csv
# us_emissions: data/interim/us_emi.csv

defaults:
  - dataset: CN

tmp: data/interim/ordered_province_daily.csv
aqi: data/interim/aqi.csv
save_arrays_EDA: False

device: cuda:0
log_step: 20

# Albation study
TNE: False
dynamic_embed: True
attention_layer: True
gru_layer: True
saved_model_path: # outputs/AGCRN_time_dependent_matrix_laplacian/06-29_11-08-05_DSTGCRN_1d_test_seed42/best_model.pth

